name: GIT TESTING


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  generate_api_docs:
    name: Generate API Docs
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CICD_TOKEN }}
          persist-credentials: false

      - name: Create Commit
        run: |
          git config --global user.email "${{ vars.GIT_CONFIG_EMAIL }}";
          git config --global user.name "Velaptor Docs Github Actions - (On behalf of Calvin Wilkinson)";
          
          git add *.*;
          git commit --allow-empty -m "Test Commit";
          git push;
