name: Fork PR Testing


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    branches: master


jobs:
  create_and_cache_data:
    name: Create and cache data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35.x

      - name:  Run Script
        run: |
          Write-Host "::notice::Workspace Dir Path: ${{ github.workspace }}";

          Write-Host "::notice::Repo Var: ${{ vars.GIT_CONFIG_EMAIL }}";
          Write-Host "::notice::Org Var: ${{ vars.ORGANIZATION_NAME }}";

          deno run `
            -A `
          "${{ github.workspace }}/.github/cicd/script-run-test.ts";
