name: Fork PR Testing


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  create_and_cache_data:
    name: Create and cache data
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35.x

      - name:  Run Script
        run: |
          deno run `
            -A
          "${{ github.workspace }}/.github/cicd/script-run-tests.ts";
