name: Cache Testing


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  create_and_cache_data:
    name: Create and cache data
    runs-on: ubuntu-latest
    steps:
      - name:  Create File
        run: |
          # Create a directory
          New-Item -Path "./test" -ItemType "directory" -Force;
          
          # Create a file in the previous directory and add the text 'hello-world' to the file
          New-Item -Path "./test/test-file.txt" -ItemType "file" -Force;
          Add-Content -Path "./test/test-file.txt" -Value "asdfasdf";    

      - name: Cache New Dir
        uses: actions/cache@v2
        with:
          key: "my-cache"
          path: "./test"
    
  print_cached_data:
    name: Print cached data
    runs-on: ubuntu-latest
    steps:
      - name:  Print Cached Data
        run: |
          # Print the contents of the cached directory
          Write-Host Get-Content -Path "./test/test-file.txt";
